---
name: Main Workflow
on:
  push:
    branches:
      - aetion
  workflow_dispatch:
  repository_dispatch:
    types: main  
jobs:
  main:
    runs-on:
      group: dev
      labels: [self-hosted, dev]
    name: Aetion Projects Service
    steps:
      - name: Aetion Build & Deploy
        uses: aetion/actions@main
        with:
          unified: true
          mavenCommand: -B -C -V -ntp -DskipTests -Dhttp.keepAlive=false -e clean deploy
